id: IECF8D308
default_language: es
source: https://www.lotsawahouse.org
initial_creation_type: web_scrap
imported: 2023-01-04 11:27:33.203125
last_modified: 2023-01-04 11:27:33.203132
source_metadata:
  collections:
  - Adzom Gyalse Series
  - Works of Tibetan Masters
bases:
  BD44:
    title: 'Advice for Beginners: How to Overcome Obstacles to Meditation'
    base_file: BD44.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
